version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:14

    working_directory: ~/repo

    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: npm install
      - run:
          name: Build React App
          command: npm run build

  deploy:
    docker:
      - image: circleci/node:14

    working_directory: ~/repo

    steps:
      - run:
          name: Install SSH Client
          command: sudo apt-get install -y openssh-client

      - run:
          name: Deploy to EC2
          command: |
           ssh -v -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null bitnami@54.172.183.153 'cd /home/bitnami/resy-sniper-frontend && git pull origin main && sudo cp -r dist/ /var/www/html/ && pm2 reload all'

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
