version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:14

    working_directory: ~/repo

    steps:
      - checkout
      - run:
          name: Install PM2
          command: npm install -g pm2 --prefix=~/.npm-global

  deploy:
    docker:
      - image: circleci/node:14

    working_directory: ~/repo

    steps:
      - run:
          name: Install SSH Client
          command: |
            sudo apt-get install -y openssh-client
      - checkout
      - run:
          name: Install Dependencies
          command: npm install
      - run:
          name: Install PM2
          command: npm install -g pm2 --prefix=~/.npm-global
      - run:
          name: Deploy to EC2
          command: |
            ssh -v -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null bitnami@54.172.183.153 << 'EOF'
            cd /home/bitnami/resy-sniper-frontend
            git pull origin main

            npm install
            npm run build

            sudo cp -r dist/ /var/www/html/
            /home/bitnami/.nvm/versions/node/v14.21.3/bin/pm2 reload all
            EOF

 
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
