version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:14.17
    steps:
      - checkout
      - run:
          name: "Install Dependencies"
          command: npm install
      - run:
          name: "Build Step"
          command: npm run build

  deploy_staging:
    docker:
      - image: cimg/node:14.17
    steps:
      - checkout
      - run:
          name: "Set SSH Key Permissions"
          command: chmod 600 /path/to/your/private/key
      - run:
          name: Deploy to Staging 
          command: |
            ssh -i "$CIRCLECI_SSH_KEY" ubuntu@18.219.242.133 "cd /path/to/staging/frontend && git pull origin staging && npm install && npm run build && serve -s build -p 3001"

workflows:
  build_and_deploy:
    jobs:
      - build
      - deploy_staging:
          requires:
            - build
          filters:
            branches:
              only: main
