version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:14.21.3

    working_directory: ~/repo

    steps:
      - checkout
      - run:
          name: Install PM2
          command: npm install -g pm2 --prefix=~/.npm-global

  deploy_staging:
    docker:
      - image: cimg/node:14.21.3
    working_directory: ~/repo
    steps:
      - attach_workspace:
          at: ~/repo
      - run:
          name: Deploy to Staging
          command: |
            ssh -v -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null bitnami@54.172.183.153 "source ~/.nvm/nvm.sh && nvm use 14.21.3 && cd /home/bitnami/resy-sniper-frontend && git pull origin staging && npm install && npm run build && sudo cp -r dist/ /var/www/html/ && pm2 reload all"

            echo "Deploying to Staging"
  deploy_production:
    docker:
      - image: cimg/node:14.21.3
    working_directory: ~/repo
    steps:
      - attach_workspace:
          at: ~/repo
      - run:
          name: Deploy to Production
          command: |
            # Your production deployment script here
            ssh -v -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null bitnami@54.156.213.45 "source ~/.nvm/nvm.sh && nvm use 14.21.3 && cd /home/bitnami/resy-sniper-frontend && git pull origin master && npm install && npm run build && sudo cp -r dist/ /var/www/html/ && pm2 reload all"
            echo "Deploying to Production"

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy_staging:
          requires:
            - build
          filters:
            branches:
              only: staging
      - deploy_production:
          requires:
            - build
          filters:
            branches:
              only: master