version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:14.17

    working_directory: ~/repo

    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: npm install

      - run:
          name: Install PM2
          command: npm install -g pm2 --prefix=~/.npm-global

      - run:
          name: Build React App
          command: npm run build

  deploy:
    docker:
      - image: circleci/node:14.17

    working_directory: ~/repo

    steps:
      - run:
          name: Install SSH Client
          command: sudo apt-get install -y openssh-client
      - checkout

      - run:
          name: Install Dependencies
          command: npm install
      - run:
          name: Install PM2
          command: npm install -g pm2 --prefix=~/.npm-global

      - run:
          name: Deploy to EC2
          command: |
            ssh -v -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null bitnami@54.172.183.153 'source /root/.nvm/nvm.sh && export NVM_DIR="/root/.nvm" && [ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh" && cd /home/bitnami/resy-sniper-frontend && git pull origin main && cd /var/www/html/ && sudo cp -r /home/bitnami/resy-sniper-frontend/dist/ /var/www/html/ && sudo /root/.nvm/versions/node/v21.6.1/lib/node_modules/pm2/bin/pm2 restart all'

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
