version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:14.21.3
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: npm install
      - run:
          name: Build
          command: npm run build
      - persist_to_workspace:
          root: ~/repo
          paths:
            - .

  deploy_staging:
    docker:
      - image: cimg/node:14.21.3
    working_directory: ~/repo
    steps:
      - attach_workspace:
          at: ~/repo
      - run:
          name: Deploy to Staging
          command: |
            # Your staging deployment script here
            echo "Deploying to Staging"

  deploy_production:
    docker:
      - image: cimg/node:14.21.3
    working_directory: ~/repo
    steps:
      - attach_workspace:
          at: ~/repo
      - run:
          name: Deploy to Production
          command: |
            # Your production deployment script here
            echo "Deploying to Production"

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy_staging:
          requires:
            - build
          filters:
            branches:
              only: staging
      - deploy_production:
          requires:
            - build
          filters:
            branches:
              only: master
