version: 2.1

jobs:
  build:
    docker:
      - image: node:14  # Use the Node.js version required by your project
    steps:
      - checkout
      - run:
          name: "Install Dependencies"
          command: npm install
