version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:14.17
    steps:
      - checkout
      - run:
          name: "Install Dependencies"
          command: npm install
      - run:
          name: "Build Step"
          command: npm run build

  deploy_staging:
    docker:
      - image: cimg/node:14.17
    steps:
      - checkout
      - run:
          name: Deploy to Staging
          command: |
            ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null bitnami@44.204.147.206 "cd /path/to/staging/frontend && git pull origin staging && npm install && npm run build && serve -s build -p 3001"

  deploy_production:
    resource_class: medium+
    docker:
      - image: cimg/node:14.17
    steps:
      - checkout
      - run:
          name: Deploy to Production
          command: |
            ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null bitnami@3.226.164.240 "cd /path/to/production/frontend && git pull origin master && npm install && npm run build && serve -s build -p 3002"

workflows:
  build_and_deploy:
    jobs:
      - build
      - deploy_staging:
          requires:
            - build
          filters:
            branches:
              only: staging
      - deploy_production:
          requires:
            - build
          filters:
            branches:
              only: master
