version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:14.17
    steps:
      - checkout
      - run:
          name: "Install Dependencies"
          command: npm install
      - run:
          name: "Build Step"
          command: npm run build

  deploy_staging:
    docker:
      - image: cimg/node:14.17
    steps:
      - checkout
      - run:
         steps:
      - checkout
      - run:
          name: Deploy to Staging
          command: |
            ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null ubuntu@18.219.242.133 "cd /home/bitnami/resysniperpublic && git pull origin staging && sudo systemctl restart apache2"

workflows:
  build_and_deploy:
    jobs:
      - build
      - deploy_staging:
          requires:
            - build
          filters:
            branches:
              only: main
